### ISSUE TITLE
Azure hosting

### ISSUE THREAD

**Issue by aoberoi** [slackapi/hubot-slack#459]
### Description

Azure-based hosting is currently broken. After some investigation in #283, we don't yet know if this is specific to `hubot-slack`, or if this is an issue with commonly used deployment instructions including the [official instructions in hubot's documentation](https://hubot.github.com/docs/deploying/azure/).

This issue will help organize the tasks related to further investigate and resolve this issue, and improve the experience of deploying Hubot to Azure.

**Subtasks**:

- [ ] Investigate whether issue is resolved by using the Azure CLI 2.0 (instead of the older Azure CLI). This will include using the Azure Resource Management APIs (instead of the Azure Service Management APIs) and building against App Services' Azure Web Apps (instead of Azure Web Sites).
- [ ] Investigate if the issue is resolved by choosing the Linux platform instead of the Windows platform. This could be a short-term fix, but we should still strive for Windows compatibility.
- [ ] Research options for loading the `hubot` dependency (see #137, #138) and see if they are viable fixes for the issue.
- [ ] Create an Azure Resource Management template for Hubot and distribute it in the Microsoft marketplace
- [ ] Contribute updated deployment instructions to hubotio/hubot docs.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
Application used to reproduce the issue (the git history is useful too): https://github.com/aoberoi/azure-hubot

The error is visible in the "Log Stream" view of the app from within the Azure Dashboard. In order to trigger the error, you visit the `/test` endpoint, which causes Azure to run the node program, which then crashes with the following message:

```
[Wed Jan 24 2018 01:28:38 GMT+0000 (Coordinated Universal Time)] DEBUG Loading adapter slack

[Wed Jan 24 2018 01:28:38 GMT+0000 (Coordinated Universal Time)] ERROR Cannot load adapter slack - Error: Cannot find module 'hubot'
```

I've tried to use environment variables `HUBOT_LOG_LEVEL=debug` and [`NODE_DEBUG=module`](http://www.juliengilli.com/2013/05/26/Using-Node.js-NODE_DEBUG-for-fun-and-profit/), but I don't get any more information than that.

**Comment by aoberoi** [comment]
Actually, setting those environment variables from the Azure dashboard doesn't seem effective. Adding them from the CLI yielded lots more logs to look into. Will take some time to find the right module load: https://gist.github.com/aoberoi/f22ce55759aa8f93ea88e39b22c51571

**Comment by aoberoi** [comment]
Open question: why doesn't the deploy script use `bin/hubot.cmd` in the hubot app template?

**Comment by aoberoi** [comment]
The most interesting part of the log is in these three lines:

```
MODULE 11880: looking for "D:\\home\\site\\wwwroot\\node_modules\\hubot-slack\\src\\bot" in ["D:\\home\\site\\wwwroot\\node_modules\\hubot-slack"]

MODULE 11880: Module._load REQUEST hubot parent: .

MODULE 11880: looking for "hubot" in ["D:\\Program Files (x86)\\iisnode\\node_modules","D:\\Program Files (x86)\\node_modules","D:\\node_modules","D:\\local\\UserProfile\\.node_modules","D:\\local\\UserProfile\\.node_libraries","D:\\Program Files (x86)\\nodejs\\8.9.3\\lib\\node"]
```

Notice how instead of looking for the 'hubot' module in the "D:\home\site\wwwroot\node_modules", where it would have been found, the `require.main.require` leads node to search inside "D:\Program Files (x86)\iisnode\node_modules", where it doesn't exist. So there's some unexpected behavior where Azure is copying most of the program into this "D:\home\site\wwwroot\" directory, but running `server.js` from inside the "D:\Program Files (x86)\iisnode" directory.

**Comment by aoberoi** [comment]
All signs point to a deficiency in https://github.com/projectkudu/KuduSync. Given that the project hasn't been touched in over 2 years, and that its forums haven't had any real activity in about that time, I think its safe to assume the project is dead. There's not much to be gained by engaging its maintainers and asking for changes.

At this point, it seems wise to explore what the modern deployment workflows from Azure and see if they no longer rely on KuduSync and we can rid ourselves of the issue that way.

**Comment by aoberoi** [comment]
I think I've gained some understanding after reading the following file: https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config

In iisnode there's the concept of an interceptor, which is an application that runs instead of the target application. It sounds like this file would be treated as the main module in the node process, and therefore `require.main` would be a reference to its `module` value. That would explain the lookup path and not being able to load `'hubot'`.

The question this creates is: Can we override this interceptor to be a part of the Azure Web App site?

**Comment by aoberoi** [comment]
Even if there's a good workaround with setting our own interceptor, there's some serious limitations to iisnode.

It looks like long running processes are just not considered a fitting use case for iisnode: https://github.com/tjanczuk/iisnode/issues/569. This would result in many hubot processes being spawned and killed, which means the websocket connection would frequently be opened and closed, or potentially more than one concurrent connection being open at a time.

**Comment by dude0001** [comment]
Was this ever resolved?

**Comment by dude0001** [comment]
Do you think there are still issues with this configuration? If so, I'd be interested in contributing to using web jobs. Do you have any direction or tasks that need to be done?

I have the iisnode setting [nodeprocesscountperapplication]([](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-nodejs-best-practices-and-troubleshoot-guide#nodeprocesscountperapplication)) set to one to limit the web app to one instance.  I then have the Always On option enabled in the web app itself.
 
![image](https://user-images.githubusercontent.com/148839/42739978-80e35a88-886e-11e8-9898-c4780a05796e.png).

**Comment by aoberoi** [comment]
@dude0001 thanks for point out these settings, i wasn't aware!

the combination of these two settings would indeed satisfy all my current concerns. of course, i can't speak from experience of running a hubot instance with these, so if you're willing to do this and report back any issues, we would be very grateful.

specifically, the nodeProcessCountPerApplication sounds like it would keep the hubot application limited to one process when sent to 1, which is actually the default, so that's great! also, the Always On option would also be necessary if we implemented the application as a WebJob. so it no longer seems to be necessary to work on a alternative of deploying hubot as a WebJob, since that route and the current implementation seem effectively the same.

if you'd like to contribute even further, here are a couple ways you can:

1. Help us create an Azure Resource Management template for Hubot and distribute it in the Microsoft marketplace (see: docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy-portal#deploy-resources-from-marketplace).

2. Verify the deployment instructions to hubotio/hubot docs, and help us make suggestions to improve them. We would likely want to mention the Always On option (since its not default).

**Comment by aoberoi** [comment]
I've updated the summary of this issue to reflect what we've learned so far.
